"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['search_gui.py']
APP_NAME = 'article_news_update_messages'
DATA_FILES = ['./json', './com', './new_script', './tool']
OPTIONS = {
    'iconfile': 'app.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "update codes and add threading",
        # 'CFBundleIdentifier': "com.metachris.osx.sandwich",
        'CFBundleVersion': "0.2.0",
        'CFBundleShortVersionString': "0.2.0",
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
