"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['search_gui.py']
APP_NAME = 'article_news_update_messages'
DATA_FILES = ['urls.json', 'get_xiaomi_update.py', 'phantomjs', 'download_apk.py', 'create_folders.py', 'headers.json', 'get_tengxun_update.py', 'get_baidu_update.py', 'get_360_update.py', 'get_appstore_update.py']
OPTIONS = {
    'iconfile': 'app.icns',
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
